[package]
name = "mem_allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-hash-map = "0.5.6"
bitflags = "2.4.1"
pl-hlist = "1.0"
rand = "0.8.4"